# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'chartsDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Charts'
  # 自动布局框架
  pod 'SnapKit', '~> 5.0.0'
  # Pods for chartsDemo

end
